[package]
name = "test-server"
description = "WebSocket server for testing websocket-web"
version = "0.0.0"
edition = "2021"

[dependencies]
env_logger = "0.11"
futures = "0.3"
log = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26"
